/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AnalyticsProfileConfigpbAttributesInitParameters struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AnalyticsProfileConfigpbAttributesObservation struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AnalyticsProfileConfigpbAttributesParameters struct {

	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AnalyticsProfileInitParameters struct {
	ApdexResponseThreshold *string `json:"apdexResponseThreshold,omitempty" tf:"apdex_response_threshold,omitempty"`

	ApdexResponseToleratedFactor *string `json:"apdexResponseToleratedFactor,omitempty" tf:"apdex_response_tolerated_factor,omitempty"`

	ApdexRttThreshold *string `json:"apdexRttThreshold,omitempty" tf:"apdex_rtt_threshold,omitempty"`

	ApdexRttToleratedFactor *string `json:"apdexRttToleratedFactor,omitempty" tf:"apdex_rtt_tolerated_factor,omitempty"`

	ApdexRumThreshold *string `json:"apdexRumThreshold,omitempty" tf:"apdex_rum_threshold,omitempty"`

	ApdexRumToleratedFactor *string `json:"apdexRumToleratedFactor,omitempty" tf:"apdex_rum_tolerated_factor,omitempty"`

	ApdexServerResponseThreshold *string `json:"apdexServerResponseThreshold,omitempty" tf:"apdex_server_response_threshold,omitempty"`

	ApdexServerResponseToleratedFactor *string `json:"apdexServerResponseToleratedFactor,omitempty" tf:"apdex_server_response_tolerated_factor,omitempty"`

	ApdexServerRttThreshold *string `json:"apdexServerRttThreshold,omitempty" tf:"apdex_server_rtt_threshold,omitempty"`

	ApdexServerRttToleratedFactor *string `json:"apdexServerRttToleratedFactor,omitempty" tf:"apdex_server_rtt_tolerated_factor,omitempty"`

	ClientLogConfig []ClientLogConfigInitParameters `json:"clientLogConfig,omitempty" tf:"client_log_config,omitempty"`

	ClientLogStreamingConfig []ClientLogStreamingConfigInitParameters `json:"clientLogStreamingConfig,omitempty" tf:"client_log_streaming_config,omitempty"`

	ConfigpbAttributes []AnalyticsProfileConfigpbAttributesInitParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	ConnLossyOooThreshold *string `json:"connLossyOooThreshold,omitempty" tf:"conn_lossy_ooo_threshold,omitempty"`

	ConnLossyTimeoRexmtThreshold *string `json:"connLossyTimeoRexmtThreshold,omitempty" tf:"conn_lossy_timeo_rexmt_threshold,omitempty"`

	ConnLossyTotalRexmtThreshold *string `json:"connLossyTotalRexmtThreshold,omitempty" tf:"conn_lossy_total_rexmt_threshold,omitempty"`

	ConnLossyZeroWinSizeEventThreshold *string `json:"connLossyZeroWinSizeEventThreshold,omitempty" tf:"conn_lossy_zero_win_size_event_threshold,omitempty"`

	ConnServerLossyOooThreshold *string `json:"connServerLossyOooThreshold,omitempty" tf:"conn_server_lossy_ooo_threshold,omitempty"`

	ConnServerLossyTimeoRexmtThreshold *string `json:"connServerLossyTimeoRexmtThreshold,omitempty" tf:"conn_server_lossy_timeo_rexmt_threshold,omitempty"`

	ConnServerLossyTotalRexmtThreshold *string `json:"connServerLossyTotalRexmtThreshold,omitempty" tf:"conn_server_lossy_total_rexmt_threshold,omitempty"`

	ConnServerLossyZeroWinSizeEventThreshold *string `json:"connServerLossyZeroWinSizeEventThreshold,omitempty" tf:"conn_server_lossy_zero_win_size_event_threshold,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	EnableAdaptiveConfig *string `json:"enableAdaptiveConfig,omitempty" tf:"enable_adaptive_config,omitempty"`

	EnableAdvancedAnalytics *string `json:"enableAdvancedAnalytics,omitempty" tf:"enable_advanced_analytics,omitempty"`

	EnableOndemandMetrics *string `json:"enableOndemandMetrics,omitempty" tf:"enable_ondemand_metrics,omitempty"`

	EnableSeAnalytics *string `json:"enableSeAnalytics,omitempty" tf:"enable_se_analytics,omitempty"`

	EnableServerAnalytics *string `json:"enableServerAnalytics,omitempty" tf:"enable_server_analytics,omitempty"`

	EnableVsAnalytics *string `json:"enableVsAnalytics,omitempty" tf:"enable_vs_analytics,omitempty"`

	ExcludeClientCloseBeforeRequestAsError *string `json:"excludeClientCloseBeforeRequestAsError,omitempty" tf:"exclude_client_close_before_request_as_error,omitempty"`

	ExcludeDNSPolicyDropAsSignificant *string `json:"excludeDnsPolicyDropAsSignificant,omitempty" tf:"exclude_dns_policy_drop_as_significant,omitempty"`

	ExcludeGsDownAsError *string `json:"excludeGsDownAsError,omitempty" tf:"exclude_gs_down_as_error,omitempty"`

	ExcludeHTTPErrorCodes []*float64 `json:"excludeHttpErrorCodes,omitempty" tf:"exclude_http_error_codes,omitempty"`

	ExcludeInvalidDNSDomainAsError *string `json:"excludeInvalidDnsDomainAsError,omitempty" tf:"exclude_invalid_dns_domain_as_error,omitempty"`

	ExcludeInvalidDNSQueryAsError *string `json:"excludeInvalidDnsQueryAsError,omitempty" tf:"exclude_invalid_dns_query_as_error,omitempty"`

	ExcludeIssuerRevokedOcspResponsesAsError *string `json:"excludeIssuerRevokedOcspResponsesAsError,omitempty" tf:"exclude_issuer_revoked_ocsp_responses_as_error,omitempty"`

	ExcludeNoDNSRecordAsError *string `json:"excludeNoDnsRecordAsError,omitempty" tf:"exclude_no_dns_record_as_error,omitempty"`

	ExcludeNoValidGsMemberAsError *string `json:"excludeNoValidGsMemberAsError,omitempty" tf:"exclude_no_valid_gs_member_as_error,omitempty"`

	ExcludePersistenceChangeAsError *string `json:"excludePersistenceChangeAsError,omitempty" tf:"exclude_persistence_change_as_error,omitempty"`

	ExcludeRevokedOcspResponsesAsError *string `json:"excludeRevokedOcspResponsesAsError,omitempty" tf:"exclude_revoked_ocsp_responses_as_error,omitempty"`

	ExcludeSIPErrorCodes []*float64 `json:"excludeSipErrorCodes,omitempty" tf:"exclude_sip_error_codes,omitempty"`

	ExcludeServerDNSErrorAsError *string `json:"excludeServerDnsErrorAsError,omitempty" tf:"exclude_server_dns_error_as_error,omitempty"`

	ExcludeServerTCPResetAsError *string `json:"excludeServerTcpResetAsError,omitempty" tf:"exclude_server_tcp_reset_as_error,omitempty"`

	ExcludeStaleOcspResponsesAsError *string `json:"excludeStaleOcspResponsesAsError,omitempty" tf:"exclude_stale_ocsp_responses_as_error,omitempty"`

	ExcludeSynRetransmitAsError *string `json:"excludeSynRetransmitAsError,omitempty" tf:"exclude_syn_retransmit_as_error,omitempty"`

	ExcludeTCPResetAsError *string `json:"excludeTcpResetAsError,omitempty" tf:"exclude_tcp_reset_as_error,omitempty"`

	ExcludeUnavailableOcspResponsesAsError *string `json:"excludeUnavailableOcspResponsesAsError,omitempty" tf:"exclude_unavailable_ocsp_responses_as_error,omitempty"`

	ExcludeUnsupportedDNSQueryAsError *string `json:"excludeUnsupportedDnsQueryAsError,omitempty" tf:"exclude_unsupported_dns_query_as_error,omitempty"`

	HealthscoreMaxServerLimit *string `json:"healthscoreMaxServerLimit,omitempty" tf:"healthscore_max_server_limit,omitempty"`

	HsEventThrottleWindow *string `json:"hsEventThrottleWindow,omitempty" tf:"hs_event_throttle_window,omitempty"`

	HsMaxAnomalyPenalty *string `json:"hsMaxAnomalyPenalty,omitempty" tf:"hs_max_anomaly_penalty,omitempty"`

	HsMaxResourcesPenalty *string `json:"hsMaxResourcesPenalty,omitempty" tf:"hs_max_resources_penalty,omitempty"`

	HsMaxSecurityPenalty *string `json:"hsMaxSecurityPenalty,omitempty" tf:"hs_max_security_penalty,omitempty"`

	HsMinDosRate *string `json:"hsMinDosRate,omitempty" tf:"hs_min_dos_rate,omitempty"`

	HsPerformanceBoost *string `json:"hsPerformanceBoost,omitempty" tf:"hs_performance_boost,omitempty"`

	HsPscoreTrafficThresholdL4Client *string `json:"hsPscoreTrafficThresholdL4Client,omitempty" tf:"hs_pscore_traffic_threshold_l4_client,omitempty"`

	HsPscoreTrafficThresholdL4Server *string `json:"hsPscoreTrafficThresholdL4Server,omitempty" tf:"hs_pscore_traffic_threshold_l4_server,omitempty"`

	HsSecurityCertscoreExpired *string `json:"hsSecurityCertscoreExpired,omitempty" tf:"hs_security_certscore_expired,omitempty"`

	HsSecurityCertscoreGt30D *string `json:"hsSecurityCertscoreGt30D,omitempty" tf:"hs_security_certscore_gt30d,omitempty"`

	HsSecurityCertscoreLe07D *string `json:"hsSecurityCertscoreLe07D,omitempty" tf:"hs_security_certscore_le07d,omitempty"`

	HsSecurityCertscoreLe30D *string `json:"hsSecurityCertscoreLe30D,omitempty" tf:"hs_security_certscore_le30d,omitempty"`

	HsSecurityChainInvalidityPenalty *string `json:"hsSecurityChainInvalidityPenalty,omitempty" tf:"hs_security_chain_invalidity_penalty,omitempty"`

	HsSecurityCipherscoreEq000B *string `json:"hsSecurityCipherscoreEq000B,omitempty" tf:"hs_security_cipherscore_eq000b,omitempty"`

	HsSecurityCipherscoreGe128B *string `json:"hsSecurityCipherscoreGe128B,omitempty" tf:"hs_security_cipherscore_ge128b,omitempty"`

	HsSecurityCipherscoreLt128B *string `json:"hsSecurityCipherscoreLt128B,omitempty" tf:"hs_security_cipherscore_lt128b,omitempty"`

	HsSecurityEncalgoScoreNone *string `json:"hsSecurityEncalgoScoreNone,omitempty" tf:"hs_security_encalgo_score_none,omitempty"`

	HsSecurityEncalgoScoreRc4 *string `json:"hsSecurityEncalgoScoreRc4,omitempty" tf:"hs_security_encalgo_score_rc4,omitempty"`

	HsSecurityHstsPenalty *string `json:"hsSecurityHstsPenalty,omitempty" tf:"hs_security_hsts_penalty,omitempty"`

	HsSecurityNonpfsPenalty *string `json:"hsSecurityNonpfsPenalty,omitempty" tf:"hs_security_nonpfs_penalty,omitempty"`

	HsSecurityOcspRevokedScore *string `json:"hsSecurityOcspRevokedScore,omitempty" tf:"hs_security_ocsp_revoked_score,omitempty"`

	HsSecuritySelfsignedcertPenalty *string `json:"hsSecuritySelfsignedcertPenalty,omitempty" tf:"hs_security_selfsignedcert_penalty,omitempty"`

	HsSecuritySsl30Score *string `json:"hsSecuritySsl30Score,omitempty" tf:"hs_security_ssl30_score,omitempty"`

	HsSecurityTls10Score *string `json:"hsSecurityTls10Score,omitempty" tf:"hs_security_tls10_score,omitempty"`

	HsSecurityTls11Score *string `json:"hsSecurityTls11Score,omitempty" tf:"hs_security_tls11_score,omitempty"`

	HsSecurityTls12Score *string `json:"hsSecurityTls12Score,omitempty" tf:"hs_security_tls12_score,omitempty"`

	HsSecurityTls13Score *string `json:"hsSecurityTls13Score,omitempty" tf:"hs_security_tls13_score,omitempty"`

	HsSecurityWeakSignatureAlgoPenalty *string `json:"hsSecurityWeakSignatureAlgoPenalty,omitempty" tf:"hs_security_weak_signature_algo_penalty,omitempty"`

	LatencyAuditProps []LatencyAuditPropsInitParameters `json:"latencyAuditProps,omitempty" tf:"latency_audit_props,omitempty"`

	Markers []MarkersInitParameters `json:"markers,omitempty" tf:"markers,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OndemandMetricsIdleTimeout *string `json:"ondemandMetricsIdleTimeout,omitempty" tf:"ondemand_metrics_idle_timeout,omitempty"`

	Ranges []RangesInitParameters `json:"ranges,omitempty" tf:"ranges,omitempty"`

	RespCodeBlock []*string `json:"respCodeBlock,omitempty" tf:"resp_code_block,omitempty"`

	SIPLogDepth *string `json:"sipLogDepth,omitempty" tf:"sip_log_depth,omitempty"`

	SensitiveLogProfile []SensitiveLogProfileInitParameters `json:"sensitiveLogProfile,omitempty" tf:"sensitive_log_profile,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	TimeTrackerProps []TimeTrackerPropsInitParameters `json:"timeTrackerProps,omitempty" tf:"time_tracker_props,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AnalyticsProfileObservation struct {
	ApdexResponseThreshold *string `json:"apdexResponseThreshold,omitempty" tf:"apdex_response_threshold,omitempty"`

	ApdexResponseToleratedFactor *string `json:"apdexResponseToleratedFactor,omitempty" tf:"apdex_response_tolerated_factor,omitempty"`

	ApdexRttThreshold *string `json:"apdexRttThreshold,omitempty" tf:"apdex_rtt_threshold,omitempty"`

	ApdexRttToleratedFactor *string `json:"apdexRttToleratedFactor,omitempty" tf:"apdex_rtt_tolerated_factor,omitempty"`

	ApdexRumThreshold *string `json:"apdexRumThreshold,omitempty" tf:"apdex_rum_threshold,omitempty"`

	ApdexRumToleratedFactor *string `json:"apdexRumToleratedFactor,omitempty" tf:"apdex_rum_tolerated_factor,omitempty"`

	ApdexServerResponseThreshold *string `json:"apdexServerResponseThreshold,omitempty" tf:"apdex_server_response_threshold,omitempty"`

	ApdexServerResponseToleratedFactor *string `json:"apdexServerResponseToleratedFactor,omitempty" tf:"apdex_server_response_tolerated_factor,omitempty"`

	ApdexServerRttThreshold *string `json:"apdexServerRttThreshold,omitempty" tf:"apdex_server_rtt_threshold,omitempty"`

	ApdexServerRttToleratedFactor *string `json:"apdexServerRttToleratedFactor,omitempty" tf:"apdex_server_rtt_tolerated_factor,omitempty"`

	ClientLogConfig []ClientLogConfigObservation `json:"clientLogConfig,omitempty" tf:"client_log_config,omitempty"`

	ClientLogStreamingConfig []ClientLogStreamingConfigObservation `json:"clientLogStreamingConfig,omitempty" tf:"client_log_streaming_config,omitempty"`

	ConfigpbAttributes []AnalyticsProfileConfigpbAttributesObservation `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	ConnLossyOooThreshold *string `json:"connLossyOooThreshold,omitempty" tf:"conn_lossy_ooo_threshold,omitempty"`

	ConnLossyTimeoRexmtThreshold *string `json:"connLossyTimeoRexmtThreshold,omitempty" tf:"conn_lossy_timeo_rexmt_threshold,omitempty"`

	ConnLossyTotalRexmtThreshold *string `json:"connLossyTotalRexmtThreshold,omitempty" tf:"conn_lossy_total_rexmt_threshold,omitempty"`

	ConnLossyZeroWinSizeEventThreshold *string `json:"connLossyZeroWinSizeEventThreshold,omitempty" tf:"conn_lossy_zero_win_size_event_threshold,omitempty"`

	ConnServerLossyOooThreshold *string `json:"connServerLossyOooThreshold,omitempty" tf:"conn_server_lossy_ooo_threshold,omitempty"`

	ConnServerLossyTimeoRexmtThreshold *string `json:"connServerLossyTimeoRexmtThreshold,omitempty" tf:"conn_server_lossy_timeo_rexmt_threshold,omitempty"`

	ConnServerLossyTotalRexmtThreshold *string `json:"connServerLossyTotalRexmtThreshold,omitempty" tf:"conn_server_lossy_total_rexmt_threshold,omitempty"`

	ConnServerLossyZeroWinSizeEventThreshold *string `json:"connServerLossyZeroWinSizeEventThreshold,omitempty" tf:"conn_server_lossy_zero_win_size_event_threshold,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	EnableAdaptiveConfig *string `json:"enableAdaptiveConfig,omitempty" tf:"enable_adaptive_config,omitempty"`

	EnableAdvancedAnalytics *string `json:"enableAdvancedAnalytics,omitempty" tf:"enable_advanced_analytics,omitempty"`

	EnableOndemandMetrics *string `json:"enableOndemandMetrics,omitempty" tf:"enable_ondemand_metrics,omitempty"`

	EnableSeAnalytics *string `json:"enableSeAnalytics,omitempty" tf:"enable_se_analytics,omitempty"`

	EnableServerAnalytics *string `json:"enableServerAnalytics,omitempty" tf:"enable_server_analytics,omitempty"`

	EnableVsAnalytics *string `json:"enableVsAnalytics,omitempty" tf:"enable_vs_analytics,omitempty"`

	ExcludeClientCloseBeforeRequestAsError *string `json:"excludeClientCloseBeforeRequestAsError,omitempty" tf:"exclude_client_close_before_request_as_error,omitempty"`

	ExcludeDNSPolicyDropAsSignificant *string `json:"excludeDnsPolicyDropAsSignificant,omitempty" tf:"exclude_dns_policy_drop_as_significant,omitempty"`

	ExcludeGsDownAsError *string `json:"excludeGsDownAsError,omitempty" tf:"exclude_gs_down_as_error,omitempty"`

	ExcludeHTTPErrorCodes []*float64 `json:"excludeHttpErrorCodes,omitempty" tf:"exclude_http_error_codes,omitempty"`

	ExcludeInvalidDNSDomainAsError *string `json:"excludeInvalidDnsDomainAsError,omitempty" tf:"exclude_invalid_dns_domain_as_error,omitempty"`

	ExcludeInvalidDNSQueryAsError *string `json:"excludeInvalidDnsQueryAsError,omitempty" tf:"exclude_invalid_dns_query_as_error,omitempty"`

	ExcludeIssuerRevokedOcspResponsesAsError *string `json:"excludeIssuerRevokedOcspResponsesAsError,omitempty" tf:"exclude_issuer_revoked_ocsp_responses_as_error,omitempty"`

	ExcludeNoDNSRecordAsError *string `json:"excludeNoDnsRecordAsError,omitempty" tf:"exclude_no_dns_record_as_error,omitempty"`

	ExcludeNoValidGsMemberAsError *string `json:"excludeNoValidGsMemberAsError,omitempty" tf:"exclude_no_valid_gs_member_as_error,omitempty"`

	ExcludePersistenceChangeAsError *string `json:"excludePersistenceChangeAsError,omitempty" tf:"exclude_persistence_change_as_error,omitempty"`

	ExcludeRevokedOcspResponsesAsError *string `json:"excludeRevokedOcspResponsesAsError,omitempty" tf:"exclude_revoked_ocsp_responses_as_error,omitempty"`

	ExcludeSIPErrorCodes []*float64 `json:"excludeSipErrorCodes,omitempty" tf:"exclude_sip_error_codes,omitempty"`

	ExcludeServerDNSErrorAsError *string `json:"excludeServerDnsErrorAsError,omitempty" tf:"exclude_server_dns_error_as_error,omitempty"`

	ExcludeServerTCPResetAsError *string `json:"excludeServerTcpResetAsError,omitempty" tf:"exclude_server_tcp_reset_as_error,omitempty"`

	ExcludeStaleOcspResponsesAsError *string `json:"excludeStaleOcspResponsesAsError,omitempty" tf:"exclude_stale_ocsp_responses_as_error,omitempty"`

	ExcludeSynRetransmitAsError *string `json:"excludeSynRetransmitAsError,omitempty" tf:"exclude_syn_retransmit_as_error,omitempty"`

	ExcludeTCPResetAsError *string `json:"excludeTcpResetAsError,omitempty" tf:"exclude_tcp_reset_as_error,omitempty"`

	ExcludeUnavailableOcspResponsesAsError *string `json:"excludeUnavailableOcspResponsesAsError,omitempty" tf:"exclude_unavailable_ocsp_responses_as_error,omitempty"`

	ExcludeUnsupportedDNSQueryAsError *string `json:"excludeUnsupportedDnsQueryAsError,omitempty" tf:"exclude_unsupported_dns_query_as_error,omitempty"`

	HealthscoreMaxServerLimit *string `json:"healthscoreMaxServerLimit,omitempty" tf:"healthscore_max_server_limit,omitempty"`

	HsEventThrottleWindow *string `json:"hsEventThrottleWindow,omitempty" tf:"hs_event_throttle_window,omitempty"`

	HsMaxAnomalyPenalty *string `json:"hsMaxAnomalyPenalty,omitempty" tf:"hs_max_anomaly_penalty,omitempty"`

	HsMaxResourcesPenalty *string `json:"hsMaxResourcesPenalty,omitempty" tf:"hs_max_resources_penalty,omitempty"`

	HsMaxSecurityPenalty *string `json:"hsMaxSecurityPenalty,omitempty" tf:"hs_max_security_penalty,omitempty"`

	HsMinDosRate *string `json:"hsMinDosRate,omitempty" tf:"hs_min_dos_rate,omitempty"`

	HsPerformanceBoost *string `json:"hsPerformanceBoost,omitempty" tf:"hs_performance_boost,omitempty"`

	HsPscoreTrafficThresholdL4Client *string `json:"hsPscoreTrafficThresholdL4Client,omitempty" tf:"hs_pscore_traffic_threshold_l4_client,omitempty"`

	HsPscoreTrafficThresholdL4Server *string `json:"hsPscoreTrafficThresholdL4Server,omitempty" tf:"hs_pscore_traffic_threshold_l4_server,omitempty"`

	HsSecurityCertscoreExpired *string `json:"hsSecurityCertscoreExpired,omitempty" tf:"hs_security_certscore_expired,omitempty"`

	HsSecurityCertscoreGt30D *string `json:"hsSecurityCertscoreGt30D,omitempty" tf:"hs_security_certscore_gt30d,omitempty"`

	HsSecurityCertscoreLe07D *string `json:"hsSecurityCertscoreLe07D,omitempty" tf:"hs_security_certscore_le07d,omitempty"`

	HsSecurityCertscoreLe30D *string `json:"hsSecurityCertscoreLe30D,omitempty" tf:"hs_security_certscore_le30d,omitempty"`

	HsSecurityChainInvalidityPenalty *string `json:"hsSecurityChainInvalidityPenalty,omitempty" tf:"hs_security_chain_invalidity_penalty,omitempty"`

	HsSecurityCipherscoreEq000B *string `json:"hsSecurityCipherscoreEq000B,omitempty" tf:"hs_security_cipherscore_eq000b,omitempty"`

	HsSecurityCipherscoreGe128B *string `json:"hsSecurityCipherscoreGe128B,omitempty" tf:"hs_security_cipherscore_ge128b,omitempty"`

	HsSecurityCipherscoreLt128B *string `json:"hsSecurityCipherscoreLt128B,omitempty" tf:"hs_security_cipherscore_lt128b,omitempty"`

	HsSecurityEncalgoScoreNone *string `json:"hsSecurityEncalgoScoreNone,omitempty" tf:"hs_security_encalgo_score_none,omitempty"`

	HsSecurityEncalgoScoreRc4 *string `json:"hsSecurityEncalgoScoreRc4,omitempty" tf:"hs_security_encalgo_score_rc4,omitempty"`

	HsSecurityHstsPenalty *string `json:"hsSecurityHstsPenalty,omitempty" tf:"hs_security_hsts_penalty,omitempty"`

	HsSecurityNonpfsPenalty *string `json:"hsSecurityNonpfsPenalty,omitempty" tf:"hs_security_nonpfs_penalty,omitempty"`

	HsSecurityOcspRevokedScore *string `json:"hsSecurityOcspRevokedScore,omitempty" tf:"hs_security_ocsp_revoked_score,omitempty"`

	HsSecuritySelfsignedcertPenalty *string `json:"hsSecuritySelfsignedcertPenalty,omitempty" tf:"hs_security_selfsignedcert_penalty,omitempty"`

	HsSecuritySsl30Score *string `json:"hsSecuritySsl30Score,omitempty" tf:"hs_security_ssl30_score,omitempty"`

	HsSecurityTls10Score *string `json:"hsSecurityTls10Score,omitempty" tf:"hs_security_tls10_score,omitempty"`

	HsSecurityTls11Score *string `json:"hsSecurityTls11Score,omitempty" tf:"hs_security_tls11_score,omitempty"`

	HsSecurityTls12Score *string `json:"hsSecurityTls12Score,omitempty" tf:"hs_security_tls12_score,omitempty"`

	HsSecurityTls13Score *string `json:"hsSecurityTls13Score,omitempty" tf:"hs_security_tls13_score,omitempty"`

	HsSecurityWeakSignatureAlgoPenalty *string `json:"hsSecurityWeakSignatureAlgoPenalty,omitempty" tf:"hs_security_weak_signature_algo_penalty,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	LatencyAuditProps []LatencyAuditPropsObservation `json:"latencyAuditProps,omitempty" tf:"latency_audit_props,omitempty"`

	Markers []MarkersObservation `json:"markers,omitempty" tf:"markers,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OndemandMetricsIdleTimeout *string `json:"ondemandMetricsIdleTimeout,omitempty" tf:"ondemand_metrics_idle_timeout,omitempty"`

	Ranges []RangesObservation `json:"ranges,omitempty" tf:"ranges,omitempty"`

	RespCodeBlock []*string `json:"respCodeBlock,omitempty" tf:"resp_code_block,omitempty"`

	SIPLogDepth *string `json:"sipLogDepth,omitempty" tf:"sip_log_depth,omitempty"`

	SensitiveLogProfile []SensitiveLogProfileObservation `json:"sensitiveLogProfile,omitempty" tf:"sensitive_log_profile,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	TimeTrackerProps []TimeTrackerPropsObservation `json:"timeTrackerProps,omitempty" tf:"time_tracker_props,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AnalyticsProfileParameters struct {

	// +kubebuilder:validation:Optional
	ApdexResponseThreshold *string `json:"apdexResponseThreshold,omitempty" tf:"apdex_response_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexResponseToleratedFactor *string `json:"apdexResponseToleratedFactor,omitempty" tf:"apdex_response_tolerated_factor,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexRttThreshold *string `json:"apdexRttThreshold,omitempty" tf:"apdex_rtt_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexRttToleratedFactor *string `json:"apdexRttToleratedFactor,omitempty" tf:"apdex_rtt_tolerated_factor,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexRumThreshold *string `json:"apdexRumThreshold,omitempty" tf:"apdex_rum_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexRumToleratedFactor *string `json:"apdexRumToleratedFactor,omitempty" tf:"apdex_rum_tolerated_factor,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexServerResponseThreshold *string `json:"apdexServerResponseThreshold,omitempty" tf:"apdex_server_response_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexServerResponseToleratedFactor *string `json:"apdexServerResponseToleratedFactor,omitempty" tf:"apdex_server_response_tolerated_factor,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexServerRttThreshold *string `json:"apdexServerRttThreshold,omitempty" tf:"apdex_server_rtt_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ApdexServerRttToleratedFactor *string `json:"apdexServerRttToleratedFactor,omitempty" tf:"apdex_server_rtt_tolerated_factor,omitempty"`

	// +kubebuilder:validation:Optional
	ClientLogConfig []ClientLogConfigParameters `json:"clientLogConfig,omitempty" tf:"client_log_config,omitempty"`

	// +kubebuilder:validation:Optional
	ClientLogStreamingConfig []ClientLogStreamingConfigParameters `json:"clientLogStreamingConfig,omitempty" tf:"client_log_streaming_config,omitempty"`

	// +kubebuilder:validation:Optional
	ConfigpbAttributes []AnalyticsProfileConfigpbAttributesParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	// +kubebuilder:validation:Optional
	ConnLossyOooThreshold *string `json:"connLossyOooThreshold,omitempty" tf:"conn_lossy_ooo_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ConnLossyTimeoRexmtThreshold *string `json:"connLossyTimeoRexmtThreshold,omitempty" tf:"conn_lossy_timeo_rexmt_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ConnLossyTotalRexmtThreshold *string `json:"connLossyTotalRexmtThreshold,omitempty" tf:"conn_lossy_total_rexmt_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ConnLossyZeroWinSizeEventThreshold *string `json:"connLossyZeroWinSizeEventThreshold,omitempty" tf:"conn_lossy_zero_win_size_event_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ConnServerLossyOooThreshold *string `json:"connServerLossyOooThreshold,omitempty" tf:"conn_server_lossy_ooo_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ConnServerLossyTimeoRexmtThreshold *string `json:"connServerLossyTimeoRexmtThreshold,omitempty" tf:"conn_server_lossy_timeo_rexmt_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ConnServerLossyTotalRexmtThreshold *string `json:"connServerLossyTotalRexmtThreshold,omitempty" tf:"conn_server_lossy_total_rexmt_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ConnServerLossyZeroWinSizeEventThreshold *string `json:"connServerLossyZeroWinSizeEventThreshold,omitempty" tf:"conn_server_lossy_zero_win_size_event_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	EnableAdaptiveConfig *string `json:"enableAdaptiveConfig,omitempty" tf:"enable_adaptive_config,omitempty"`

	// +kubebuilder:validation:Optional
	EnableAdvancedAnalytics *string `json:"enableAdvancedAnalytics,omitempty" tf:"enable_advanced_analytics,omitempty"`

	// +kubebuilder:validation:Optional
	EnableOndemandMetrics *string `json:"enableOndemandMetrics,omitempty" tf:"enable_ondemand_metrics,omitempty"`

	// +kubebuilder:validation:Optional
	EnableSeAnalytics *string `json:"enableSeAnalytics,omitempty" tf:"enable_se_analytics,omitempty"`

	// +kubebuilder:validation:Optional
	EnableServerAnalytics *string `json:"enableServerAnalytics,omitempty" tf:"enable_server_analytics,omitempty"`

	// +kubebuilder:validation:Optional
	EnableVsAnalytics *string `json:"enableVsAnalytics,omitempty" tf:"enable_vs_analytics,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeClientCloseBeforeRequestAsError *string `json:"excludeClientCloseBeforeRequestAsError,omitempty" tf:"exclude_client_close_before_request_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeDNSPolicyDropAsSignificant *string `json:"excludeDnsPolicyDropAsSignificant,omitempty" tf:"exclude_dns_policy_drop_as_significant,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeGsDownAsError *string `json:"excludeGsDownAsError,omitempty" tf:"exclude_gs_down_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeHTTPErrorCodes []*float64 `json:"excludeHttpErrorCodes,omitempty" tf:"exclude_http_error_codes,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeInvalidDNSDomainAsError *string `json:"excludeInvalidDnsDomainAsError,omitempty" tf:"exclude_invalid_dns_domain_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeInvalidDNSQueryAsError *string `json:"excludeInvalidDnsQueryAsError,omitempty" tf:"exclude_invalid_dns_query_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeIssuerRevokedOcspResponsesAsError *string `json:"excludeIssuerRevokedOcspResponsesAsError,omitempty" tf:"exclude_issuer_revoked_ocsp_responses_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeNoDNSRecordAsError *string `json:"excludeNoDnsRecordAsError,omitempty" tf:"exclude_no_dns_record_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeNoValidGsMemberAsError *string `json:"excludeNoValidGsMemberAsError,omitempty" tf:"exclude_no_valid_gs_member_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludePersistenceChangeAsError *string `json:"excludePersistenceChangeAsError,omitempty" tf:"exclude_persistence_change_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeRevokedOcspResponsesAsError *string `json:"excludeRevokedOcspResponsesAsError,omitempty" tf:"exclude_revoked_ocsp_responses_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeSIPErrorCodes []*float64 `json:"excludeSipErrorCodes,omitempty" tf:"exclude_sip_error_codes,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeServerDNSErrorAsError *string `json:"excludeServerDnsErrorAsError,omitempty" tf:"exclude_server_dns_error_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeServerTCPResetAsError *string `json:"excludeServerTcpResetAsError,omitempty" tf:"exclude_server_tcp_reset_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeStaleOcspResponsesAsError *string `json:"excludeStaleOcspResponsesAsError,omitempty" tf:"exclude_stale_ocsp_responses_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeSynRetransmitAsError *string `json:"excludeSynRetransmitAsError,omitempty" tf:"exclude_syn_retransmit_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeTCPResetAsError *string `json:"excludeTcpResetAsError,omitempty" tf:"exclude_tcp_reset_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeUnavailableOcspResponsesAsError *string `json:"excludeUnavailableOcspResponsesAsError,omitempty" tf:"exclude_unavailable_ocsp_responses_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeUnsupportedDNSQueryAsError *string `json:"excludeUnsupportedDnsQueryAsError,omitempty" tf:"exclude_unsupported_dns_query_as_error,omitempty"`

	// +kubebuilder:validation:Optional
	HealthscoreMaxServerLimit *string `json:"healthscoreMaxServerLimit,omitempty" tf:"healthscore_max_server_limit,omitempty"`

	// +kubebuilder:validation:Optional
	HsEventThrottleWindow *string `json:"hsEventThrottleWindow,omitempty" tf:"hs_event_throttle_window,omitempty"`

	// +kubebuilder:validation:Optional
	HsMaxAnomalyPenalty *string `json:"hsMaxAnomalyPenalty,omitempty" tf:"hs_max_anomaly_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	HsMaxResourcesPenalty *string `json:"hsMaxResourcesPenalty,omitempty" tf:"hs_max_resources_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	HsMaxSecurityPenalty *string `json:"hsMaxSecurityPenalty,omitempty" tf:"hs_max_security_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	HsMinDosRate *string `json:"hsMinDosRate,omitempty" tf:"hs_min_dos_rate,omitempty"`

	// +kubebuilder:validation:Optional
	HsPerformanceBoost *string `json:"hsPerformanceBoost,omitempty" tf:"hs_performance_boost,omitempty"`

	// +kubebuilder:validation:Optional
	HsPscoreTrafficThresholdL4Client *string `json:"hsPscoreTrafficThresholdL4Client,omitempty" tf:"hs_pscore_traffic_threshold_l4_client,omitempty"`

	// +kubebuilder:validation:Optional
	HsPscoreTrafficThresholdL4Server *string `json:"hsPscoreTrafficThresholdL4Server,omitempty" tf:"hs_pscore_traffic_threshold_l4_server,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityCertscoreExpired *string `json:"hsSecurityCertscoreExpired,omitempty" tf:"hs_security_certscore_expired,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityCertscoreGt30D *string `json:"hsSecurityCertscoreGt30D,omitempty" tf:"hs_security_certscore_gt30d,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityCertscoreLe07D *string `json:"hsSecurityCertscoreLe07D,omitempty" tf:"hs_security_certscore_le07d,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityCertscoreLe30D *string `json:"hsSecurityCertscoreLe30D,omitempty" tf:"hs_security_certscore_le30d,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityChainInvalidityPenalty *string `json:"hsSecurityChainInvalidityPenalty,omitempty" tf:"hs_security_chain_invalidity_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityCipherscoreEq000B *string `json:"hsSecurityCipherscoreEq000B,omitempty" tf:"hs_security_cipherscore_eq000b,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityCipherscoreGe128B *string `json:"hsSecurityCipherscoreGe128B,omitempty" tf:"hs_security_cipherscore_ge128b,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityCipherscoreLt128B *string `json:"hsSecurityCipherscoreLt128B,omitempty" tf:"hs_security_cipherscore_lt128b,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityEncalgoScoreNone *string `json:"hsSecurityEncalgoScoreNone,omitempty" tf:"hs_security_encalgo_score_none,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityEncalgoScoreRc4 *string `json:"hsSecurityEncalgoScoreRc4,omitempty" tf:"hs_security_encalgo_score_rc4,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityHstsPenalty *string `json:"hsSecurityHstsPenalty,omitempty" tf:"hs_security_hsts_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityNonpfsPenalty *string `json:"hsSecurityNonpfsPenalty,omitempty" tf:"hs_security_nonpfs_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityOcspRevokedScore *string `json:"hsSecurityOcspRevokedScore,omitempty" tf:"hs_security_ocsp_revoked_score,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecuritySelfsignedcertPenalty *string `json:"hsSecuritySelfsignedcertPenalty,omitempty" tf:"hs_security_selfsignedcert_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecuritySsl30Score *string `json:"hsSecuritySsl30Score,omitempty" tf:"hs_security_ssl30_score,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityTls10Score *string `json:"hsSecurityTls10Score,omitempty" tf:"hs_security_tls10_score,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityTls11Score *string `json:"hsSecurityTls11Score,omitempty" tf:"hs_security_tls11_score,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityTls12Score *string `json:"hsSecurityTls12Score,omitempty" tf:"hs_security_tls12_score,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityTls13Score *string `json:"hsSecurityTls13Score,omitempty" tf:"hs_security_tls13_score,omitempty"`

	// +kubebuilder:validation:Optional
	HsSecurityWeakSignatureAlgoPenalty *string `json:"hsSecurityWeakSignatureAlgoPenalty,omitempty" tf:"hs_security_weak_signature_algo_penalty,omitempty"`

	// +kubebuilder:validation:Optional
	LatencyAuditProps []LatencyAuditPropsParameters `json:"latencyAuditProps,omitempty" tf:"latency_audit_props,omitempty"`

	// +kubebuilder:validation:Optional
	Markers []MarkersParameters `json:"markers,omitempty" tf:"markers,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	OndemandMetricsIdleTimeout *string `json:"ondemandMetricsIdleTimeout,omitempty" tf:"ondemand_metrics_idle_timeout,omitempty"`

	// +kubebuilder:validation:Optional
	Ranges []RangesParameters `json:"ranges,omitempty" tf:"ranges,omitempty"`

	// +kubebuilder:validation:Optional
	RespCodeBlock []*string `json:"respCodeBlock,omitempty" tf:"resp_code_block,omitempty"`

	// +kubebuilder:validation:Optional
	SIPLogDepth *string `json:"sipLogDepth,omitempty" tf:"sip_log_depth,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveLogProfile []SensitiveLogProfileParameters `json:"sensitiveLogProfile,omitempty" tf:"sensitive_log_profile,omitempty"`

	// +kubebuilder:validation:Optional
	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	// +kubebuilder:validation:Optional
	TimeTrackerProps []TimeTrackerPropsParameters `json:"timeTrackerProps,omitempty" tf:"time_tracker_props,omitempty"`

	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ClientLogConfigInitParameters struct {
	EnableSignificantLogCollection *string `json:"enableSignificantLogCollection,omitempty" tf:"enable_significant_log_collection,omitempty"`

	FilteredLogProcessing *string `json:"filteredLogProcessing,omitempty" tf:"filtered_log_processing,omitempty"`

	NonSignificantLogProcessing *string `json:"nonSignificantLogProcessing,omitempty" tf:"non_significant_log_processing,omitempty"`

	SignificantLogProcessing *string `json:"significantLogProcessing,omitempty" tf:"significant_log_processing,omitempty"`
}

type ClientLogConfigObservation struct {
	EnableSignificantLogCollection *string `json:"enableSignificantLogCollection,omitempty" tf:"enable_significant_log_collection,omitempty"`

	FilteredLogProcessing *string `json:"filteredLogProcessing,omitempty" tf:"filtered_log_processing,omitempty"`

	NonSignificantLogProcessing *string `json:"nonSignificantLogProcessing,omitempty" tf:"non_significant_log_processing,omitempty"`

	SignificantLogProcessing *string `json:"significantLogProcessing,omitempty" tf:"significant_log_processing,omitempty"`
}

type ClientLogConfigParameters struct {

	// +kubebuilder:validation:Optional
	EnableSignificantLogCollection *string `json:"enableSignificantLogCollection,omitempty" tf:"enable_significant_log_collection,omitempty"`

	// +kubebuilder:validation:Optional
	FilteredLogProcessing *string `json:"filteredLogProcessing,omitempty" tf:"filtered_log_processing,omitempty"`

	// +kubebuilder:validation:Optional
	NonSignificantLogProcessing *string `json:"nonSignificantLogProcessing,omitempty" tf:"non_significant_log_processing,omitempty"`

	// +kubebuilder:validation:Optional
	SignificantLogProcessing *string `json:"significantLogProcessing,omitempty" tf:"significant_log_processing,omitempty"`
}

type ClientLogStreamingConfigInitParameters struct {
	ExternalServer *string `json:"externalServer,omitempty" tf:"external_server,omitempty"`

	ExternalServerPort *string `json:"externalServerPort,omitempty" tf:"external_server_port,omitempty"`

	FormatConfig []FormatConfigInitParameters `json:"formatConfig,omitempty" tf:"format_config,omitempty"`

	LogTypesToSend *string `json:"logTypesToSend,omitempty" tf:"log_types_to_send,omitempty"`

	MarkerKeys []MarkerKeysInitParameters `json:"markerKeys,omitempty" tf:"marker_keys,omitempty"`

	MaxLogsPerSecond *string `json:"maxLogsPerSecond,omitempty" tf:"max_logs_per_second,omitempty"`

	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	SyslogConfig []SyslogConfigInitParameters `json:"syslogConfig,omitempty" tf:"syslog_config,omitempty"`
}

type ClientLogStreamingConfigObservation struct {
	ExternalServer *string `json:"externalServer,omitempty" tf:"external_server,omitempty"`

	ExternalServerPort *string `json:"externalServerPort,omitempty" tf:"external_server_port,omitempty"`

	FormatConfig []FormatConfigObservation `json:"formatConfig,omitempty" tf:"format_config,omitempty"`

	LogTypesToSend *string `json:"logTypesToSend,omitempty" tf:"log_types_to_send,omitempty"`

	MarkerKeys []MarkerKeysObservation `json:"markerKeys,omitempty" tf:"marker_keys,omitempty"`

	MaxLogsPerSecond *string `json:"maxLogsPerSecond,omitempty" tf:"max_logs_per_second,omitempty"`

	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	SyslogConfig []SyslogConfigObservation `json:"syslogConfig,omitempty" tf:"syslog_config,omitempty"`
}

type ClientLogStreamingConfigParameters struct {

	// +kubebuilder:validation:Optional
	ExternalServer *string `json:"externalServer" tf:"external_server,omitempty"`

	// +kubebuilder:validation:Optional
	ExternalServerPort *string `json:"externalServerPort,omitempty" tf:"external_server_port,omitempty"`

	// +kubebuilder:validation:Optional
	FormatConfig []FormatConfigParameters `json:"formatConfig,omitempty" tf:"format_config,omitempty"`

	// +kubebuilder:validation:Optional
	LogTypesToSend *string `json:"logTypesToSend,omitempty" tf:"log_types_to_send,omitempty"`

	// +kubebuilder:validation:Optional
	MarkerKeys []MarkerKeysParameters `json:"markerKeys,omitempty" tf:"marker_keys,omitempty"`

	// +kubebuilder:validation:Optional
	MaxLogsPerSecond *string `json:"maxLogsPerSecond,omitempty" tf:"max_logs_per_second,omitempty"`

	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// +kubebuilder:validation:Optional
	SyslogConfig []SyslogConfigParameters `json:"syslogConfig,omitempty" tf:"syslog_config,omitempty"`
}

type FormatConfigInitParameters struct {
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	IncludedFields []*string `json:"includedFields,omitempty" tf:"included_fields,omitempty"`
}

type FormatConfigObservation struct {
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	IncludedFields []*string `json:"includedFields,omitempty" tf:"included_fields,omitempty"`
}

type FormatConfigParameters struct {

	// +kubebuilder:validation:Optional
	Format *string `json:"format" tf:"format,omitempty"`

	// +kubebuilder:validation:Optional
	IncludedFields []*string `json:"includedFields,omitempty" tf:"included_fields,omitempty"`
}

type HeaderFieldRulesInitParameters struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	Match []MatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type HeaderFieldRulesObservation struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	Match []MatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type HeaderFieldRulesParameters struct {

	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	// +kubebuilder:validation:Optional
	Match []MatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type LatencyAuditPropsInitParameters struct {
	ConnEstAuditMode *string `json:"connEstAuditMode,omitempty" tf:"conn_est_audit_mode,omitempty"`

	ConnEstThreshold *string `json:"connEstThreshold,omitempty" tf:"conn_est_threshold,omitempty"`

	LatencyAuditMode *string `json:"latencyAuditMode,omitempty" tf:"latency_audit_mode,omitempty"`

	LatencyThreshold *string `json:"latencyThreshold,omitempty" tf:"latency_threshold,omitempty"`
}

type LatencyAuditPropsObservation struct {
	ConnEstAuditMode *string `json:"connEstAuditMode,omitempty" tf:"conn_est_audit_mode,omitempty"`

	ConnEstThreshold *string `json:"connEstThreshold,omitempty" tf:"conn_est_threshold,omitempty"`

	LatencyAuditMode *string `json:"latencyAuditMode,omitempty" tf:"latency_audit_mode,omitempty"`

	LatencyThreshold *string `json:"latencyThreshold,omitempty" tf:"latency_threshold,omitempty"`
}

type LatencyAuditPropsParameters struct {

	// +kubebuilder:validation:Optional
	ConnEstAuditMode *string `json:"connEstAuditMode,omitempty" tf:"conn_est_audit_mode,omitempty"`

	// +kubebuilder:validation:Optional
	ConnEstThreshold *string `json:"connEstThreshold,omitempty" tf:"conn_est_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	LatencyAuditMode *string `json:"latencyAuditMode,omitempty" tf:"latency_audit_mode,omitempty"`

	// +kubebuilder:validation:Optional
	LatencyThreshold *string `json:"latencyThreshold,omitempty" tf:"latency_threshold,omitempty"`
}

type MarkerKeysInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type MarkerKeysObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type MarkerKeysParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type MarkersInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type MarkersObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type MarkersParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Values []*string `json:"values,omitempty" tf:"values,omitempty"`
}

type MatchInitParameters struct {
	MatchCriteria *string `json:"matchCriteria,omitempty" tf:"match_criteria,omitempty"`

	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type MatchObservation struct {
	MatchCriteria *string `json:"matchCriteria,omitempty" tf:"match_criteria,omitempty"`

	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type MatchParameters struct {

	// +kubebuilder:validation:Optional
	MatchCriteria *string `json:"matchCriteria" tf:"match_criteria,omitempty"`

	// +kubebuilder:validation:Optional
	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	// +kubebuilder:validation:Optional
	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type RangesInitParameters struct {
	Begin *string `json:"begin,omitempty" tf:"begin,omitempty"`

	End *string `json:"end,omitempty" tf:"end,omitempty"`
}

type RangesObservation struct {
	Begin *string `json:"begin,omitempty" tf:"begin,omitempty"`

	End *string `json:"end,omitempty" tf:"end,omitempty"`
}

type RangesParameters struct {

	// +kubebuilder:validation:Optional
	Begin *string `json:"begin" tf:"begin,omitempty"`

	// +kubebuilder:validation:Optional
	End *string `json:"end" tf:"end,omitempty"`
}

type SensitiveLogProfileInitParameters struct {
	HeaderFieldRules []HeaderFieldRulesInitParameters `json:"headerFieldRules,omitempty" tf:"header_field_rules,omitempty"`

	URIQueryFieldRules []URIQueryFieldRulesInitParameters `json:"uriQueryFieldRules,omitempty" tf:"uri_query_field_rules,omitempty"`

	WafFieldRules []WafFieldRulesInitParameters `json:"wafFieldRules,omitempty" tf:"waf_field_rules,omitempty"`
}

type SensitiveLogProfileObservation struct {
	HeaderFieldRules []HeaderFieldRulesObservation `json:"headerFieldRules,omitempty" tf:"header_field_rules,omitempty"`

	URIQueryFieldRules []URIQueryFieldRulesObservation `json:"uriQueryFieldRules,omitempty" tf:"uri_query_field_rules,omitempty"`

	WafFieldRules []WafFieldRulesObservation `json:"wafFieldRules,omitempty" tf:"waf_field_rules,omitempty"`
}

type SensitiveLogProfileParameters struct {

	// +kubebuilder:validation:Optional
	HeaderFieldRules []HeaderFieldRulesParameters `json:"headerFieldRules,omitempty" tf:"header_field_rules,omitempty"`

	// +kubebuilder:validation:Optional
	URIQueryFieldRules []URIQueryFieldRulesParameters `json:"uriQueryFieldRules,omitempty" tf:"uri_query_field_rules,omitempty"`

	// +kubebuilder:validation:Optional
	WafFieldRules []WafFieldRulesParameters `json:"wafFieldRules,omitempty" tf:"waf_field_rules,omitempty"`
}

type SyslogConfigInitParameters struct {
	Facility *string `json:"facility,omitempty" tf:"facility,omitempty"`

	FilteredLogSeverity *string `json:"filteredLogSeverity,omitempty" tf:"filtered_log_severity,omitempty"`

	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	NonSignificantLogSeverity *string `json:"nonSignificantLogSeverity,omitempty" tf:"non_significant_log_severity,omitempty"`

	SignificantLogSeverity *string `json:"significantLogSeverity,omitempty" tf:"significant_log_severity,omitempty"`
}

type SyslogConfigObservation struct {
	Facility *string `json:"facility,omitempty" tf:"facility,omitempty"`

	FilteredLogSeverity *string `json:"filteredLogSeverity,omitempty" tf:"filtered_log_severity,omitempty"`

	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	NonSignificantLogSeverity *string `json:"nonSignificantLogSeverity,omitempty" tf:"non_significant_log_severity,omitempty"`

	SignificantLogSeverity *string `json:"significantLogSeverity,omitempty" tf:"significant_log_severity,omitempty"`
}

type SyslogConfigParameters struct {

	// +kubebuilder:validation:Optional
	Facility *string `json:"facility,omitempty" tf:"facility,omitempty"`

	// +kubebuilder:validation:Optional
	FilteredLogSeverity *string `json:"filteredLogSeverity,omitempty" tf:"filtered_log_severity,omitempty"`

	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// +kubebuilder:validation:Optional
	NonSignificantLogSeverity *string `json:"nonSignificantLogSeverity,omitempty" tf:"non_significant_log_severity,omitempty"`

	// +kubebuilder:validation:Optional
	SignificantLogSeverity *string `json:"significantLogSeverity,omitempty" tf:"significant_log_severity,omitempty"`
}

type TimeTrackerPropsInitParameters struct {
	BeConnEstAuditMode *string `json:"beConnEstAuditMode,omitempty" tf:"be_conn_est_audit_mode,omitempty"`

	BeConnEstThreshold *string `json:"beConnEstThreshold,omitempty" tf:"be_conn_est_threshold,omitempty"`

	FeConnEstAuditMode *string `json:"feConnEstAuditMode,omitempty" tf:"fe_conn_est_audit_mode,omitempty"`

	FeConnEstThreshold *string `json:"feConnEstThreshold,omitempty" tf:"fe_conn_est_threshold,omitempty"`

	IngressSigLog *string `json:"ingressSigLog,omitempty" tf:"ingress_sig_log,omitempty"`
}

type TimeTrackerPropsObservation struct {
	BeConnEstAuditMode *string `json:"beConnEstAuditMode,omitempty" tf:"be_conn_est_audit_mode,omitempty"`

	BeConnEstThreshold *string `json:"beConnEstThreshold,omitempty" tf:"be_conn_est_threshold,omitempty"`

	FeConnEstAuditMode *string `json:"feConnEstAuditMode,omitempty" tf:"fe_conn_est_audit_mode,omitempty"`

	FeConnEstThreshold *string `json:"feConnEstThreshold,omitempty" tf:"fe_conn_est_threshold,omitempty"`

	IngressSigLog *string `json:"ingressSigLog,omitempty" tf:"ingress_sig_log,omitempty"`
}

type TimeTrackerPropsParameters struct {

	// +kubebuilder:validation:Optional
	BeConnEstAuditMode *string `json:"beConnEstAuditMode,omitempty" tf:"be_conn_est_audit_mode,omitempty"`

	// +kubebuilder:validation:Optional
	BeConnEstThreshold *string `json:"beConnEstThreshold,omitempty" tf:"be_conn_est_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	FeConnEstAuditMode *string `json:"feConnEstAuditMode,omitempty" tf:"fe_conn_est_audit_mode,omitempty"`

	// +kubebuilder:validation:Optional
	FeConnEstThreshold *string `json:"feConnEstThreshold,omitempty" tf:"fe_conn_est_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	IngressSigLog *string `json:"ingressSigLog,omitempty" tf:"ingress_sig_log,omitempty"`
}

type URIQueryFieldRulesInitParameters struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	Match []URIQueryFieldRulesMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type URIQueryFieldRulesMatchInitParameters struct {
	MatchCriteria *string `json:"matchCriteria,omitempty" tf:"match_criteria,omitempty"`

	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type URIQueryFieldRulesMatchObservation struct {
	MatchCriteria *string `json:"matchCriteria,omitempty" tf:"match_criteria,omitempty"`

	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type URIQueryFieldRulesMatchParameters struct {

	// +kubebuilder:validation:Optional
	MatchCriteria *string `json:"matchCriteria" tf:"match_criteria,omitempty"`

	// +kubebuilder:validation:Optional
	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	// +kubebuilder:validation:Optional
	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type URIQueryFieldRulesObservation struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	Match []URIQueryFieldRulesMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type URIQueryFieldRulesParameters struct {

	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	// +kubebuilder:validation:Optional
	Match []URIQueryFieldRulesMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type WafFieldRulesInitParameters struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	Match []WafFieldRulesMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type WafFieldRulesMatchInitParameters struct {
	MatchCriteria *string `json:"matchCriteria,omitempty" tf:"match_criteria,omitempty"`

	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type WafFieldRulesMatchObservation struct {
	MatchCriteria *string `json:"matchCriteria,omitempty" tf:"match_criteria,omitempty"`

	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type WafFieldRulesMatchParameters struct {

	// +kubebuilder:validation:Optional
	MatchCriteria *string `json:"matchCriteria" tf:"match_criteria,omitempty"`

	// +kubebuilder:validation:Optional
	MatchStr []*string `json:"matchStr,omitempty" tf:"match_str,omitempty"`

	// +kubebuilder:validation:Optional
	StringGroupRefs []*string `json:"stringGroupRefs,omitempty" tf:"string_group_refs,omitempty"`
}

type WafFieldRulesObservation struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	Match []WafFieldRulesMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type WafFieldRulesParameters struct {

	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Index *string `json:"index,omitempty" tf:"index,omitempty"`

	// +kubebuilder:validation:Optional
	Match []WafFieldRulesMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// AnalyticsProfileSpec defines the desired state of AnalyticsProfile
type AnalyticsProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AnalyticsProfileParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AnalyticsProfileInitParameters `json:"initProvider,omitempty"`
}

// AnalyticsProfileStatus defines the observed state of AnalyticsProfile.
type AnalyticsProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AnalyticsProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AnalyticsProfile is the Schema for the AnalyticsProfiles API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,avi}
type AnalyticsProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="name is a required parameter"
	Spec   AnalyticsProfileSpec   `json:"spec"`
	Status AnalyticsProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AnalyticsProfileList contains a list of AnalyticsProfiles
type AnalyticsProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AnalyticsProfile `json:"items"`
}

// Repository type metadata.
var (
	AnalyticsProfile_Kind             = "AnalyticsProfile"
	AnalyticsProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AnalyticsProfile_Kind}.String()
	AnalyticsProfile_KindAPIVersion   = AnalyticsProfile_Kind + "." + CRDGroupVersion.String()
	AnalyticsProfile_GroupVersionKind = CRDGroupVersion.WithKind(AnalyticsProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&AnalyticsProfile{}, &AnalyticsProfileList{})
}
