/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AlertEmailConfigConfigpbAttributesInitParameters struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AlertEmailConfigConfigpbAttributesObservation struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AlertEmailConfigConfigpbAttributesParameters struct {

	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AlertEmailConfigInitParameters struct {
	CcEmails *string `json:"ccEmails,omitempty" tf:"cc_emails,omitempty"`

	ConfigpbAttributes []AlertEmailConfigConfigpbAttributesInitParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	ToEmails *string `json:"toEmails,omitempty" tf:"to_emails,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AlertEmailConfigObservation struct {
	CcEmails *string `json:"ccEmails,omitempty" tf:"cc_emails,omitempty"`

	ConfigpbAttributes []AlertEmailConfigConfigpbAttributesObservation `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	ToEmails *string `json:"toEmails,omitempty" tf:"to_emails,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AlertEmailConfigParameters struct {

	// +kubebuilder:validation:Optional
	CcEmails *string `json:"ccEmails,omitempty" tf:"cc_emails,omitempty"`

	// +kubebuilder:validation:Optional
	ConfigpbAttributes []AlertEmailConfigConfigpbAttributesParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	// +kubebuilder:validation:Optional
	ToEmails *string `json:"toEmails,omitempty" tf:"to_emails,omitempty"`

	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

// AlertEmailConfigSpec defines the desired state of AlertEmailConfig
type AlertEmailConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AlertEmailConfigParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AlertEmailConfigInitParameters `json:"initProvider,omitempty"`
}

// AlertEmailConfigStatus defines the observed state of AlertEmailConfig.
type AlertEmailConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AlertEmailConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AlertEmailConfig is the Schema for the AlertEmailConfigs API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,avi}
type AlertEmailConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.toEmails) || has(self.initProvider.toEmails)",message="toEmails is a required parameter"
	Spec   AlertEmailConfigSpec   `json:"spec"`
	Status AlertEmailConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AlertEmailConfigList contains a list of AlertEmailConfigs
type AlertEmailConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AlertEmailConfig `json:"items"`
}

// Repository type metadata.
var (
	AlertEmailConfig_Kind             = "AlertEmailConfig"
	AlertEmailConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AlertEmailConfig_Kind}.String()
	AlertEmailConfig_KindAPIVersion   = AlertEmailConfig_Kind + "." + CRDGroupVersion.String()
	AlertEmailConfig_GroupVersionKind = CRDGroupVersion.WithKind(AlertEmailConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&AlertEmailConfig{}, &AlertEmailConfigList{})
}
