/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FileServiceInitParameters struct {
	LocalFile *string `json:"localFile,omitempty" tf:"local_file,omitempty"`

	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	Upload *bool `json:"upload,omitempty" tf:"upload,omitempty"`
}

type FileServiceObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	LocalFile *string `json:"localFile,omitempty" tf:"local_file,omitempty"`

	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	Upload *bool `json:"upload,omitempty" tf:"upload,omitempty"`
}

type FileServiceParameters struct {

	// +kubebuilder:validation:Optional
	LocalFile *string `json:"localFile,omitempty" tf:"local_file,omitempty"`

	// +kubebuilder:validation:Optional
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// +kubebuilder:validation:Optional
	Upload *bool `json:"upload,omitempty" tf:"upload,omitempty"`
}

// FileServiceSpec defines the desired state of FileService
type FileServiceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FileServiceParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FileServiceInitParameters `json:"initProvider,omitempty"`
}

// FileServiceStatus defines the observed state of FileService.
type FileServiceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FileServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// FileService is the Schema for the FileServices API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,avi}
type FileService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.localFile) || has(self.initProvider.localFile)",message="localFile is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.uri) || has(self.initProvider.uri)",message="uri is a required parameter"
	Spec   FileServiceSpec   `json:"spec"`
	Status FileServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FileServiceList contains a list of FileServices
type FileServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FileService `json:"items"`
}

// Repository type metadata.
var (
	FileService_Kind             = "FileService"
	FileService_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FileService_Kind}.String()
	FileService_KindAPIVersion   = FileService_Kind + "." + CRDGroupVersion.String()
	FileService_GroupVersionKind = CRDGroupVersion.WithKind(FileService_Kind)
)

func init() {
	SchemeBuilder.Register(&FileService{}, &FileServiceList{})
}
