/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ControllerInternalAuthInitParameters struct {
	SymmetricJwksKeys []SymmetricJwksKeysInitParameters `json:"symmetricJwksKeys,omitempty" tf:"symmetric_jwks_keys,omitempty"`
}

type ControllerInternalAuthObservation struct {
	SymmetricJwksKeys []SymmetricJwksKeysObservation `json:"symmetricJwksKeys,omitempty" tf:"symmetric_jwks_keys,omitempty"`
}

type ControllerInternalAuthParameters struct {

	// +kubebuilder:validation:Optional
	SymmetricJwksKeys []SymmetricJwksKeysParameters `json:"symmetricJwksKeys" tf:"symmetric_jwks_keys,omitempty"`
}

type JWTServerProfileConfigpbAttributesInitParameters struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type JWTServerProfileConfigpbAttributesObservation struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type JWTServerProfileConfigpbAttributesParameters struct {

	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type JWTServerProfileInitParameters struct {
	ConfigpbAttributes []JWTServerProfileConfigpbAttributesInitParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	ControllerInternalAuth []ControllerInternalAuthInitParameters `json:"controllerInternalAuth,omitempty" tf:"controller_internal_auth,omitempty"`

	IsFederated *string `json:"isFederated,omitempty" tf:"is_federated,omitempty"`

	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	JwksKeys *string `json:"jwksKeys,omitempty" tf:"jwks_keys,omitempty"`

	JwtProfileType *string `json:"jwtProfileType,omitempty" tf:"jwt_profile_type,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type JWTServerProfileObservation struct {
	ConfigpbAttributes []JWTServerProfileConfigpbAttributesObservation `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	ControllerInternalAuth []ControllerInternalAuthObservation `json:"controllerInternalAuth,omitempty" tf:"controller_internal_auth,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IsFederated *string `json:"isFederated,omitempty" tf:"is_federated,omitempty"`

	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	JwksKeys *string `json:"jwksKeys,omitempty" tf:"jwks_keys,omitempty"`

	JwtProfileType *string `json:"jwtProfileType,omitempty" tf:"jwt_profile_type,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type JWTServerProfileParameters struct {

	// +kubebuilder:validation:Optional
	ConfigpbAttributes []JWTServerProfileConfigpbAttributesParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	// +kubebuilder:validation:Optional
	ControllerInternalAuth []ControllerInternalAuthParameters `json:"controllerInternalAuth,omitempty" tf:"controller_internal_auth,omitempty"`

	// +kubebuilder:validation:Optional
	IsFederated *string `json:"isFederated,omitempty" tf:"is_federated,omitempty"`

	// +kubebuilder:validation:Optional
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// +kubebuilder:validation:Optional
	JwksKeys *string `json:"jwksKeys,omitempty" tf:"jwks_keys,omitempty"`

	// +kubebuilder:validation:Optional
	JwtProfileType *string `json:"jwtProfileType,omitempty" tf:"jwt_profile_type,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type SymmetricJwksKeysInitParameters struct {
	Alg *string `json:"alg,omitempty" tf:"alg,omitempty"`

	Kid *string `json:"kid,omitempty" tf:"kid,omitempty"`

	Kty *string `json:"kty,omitempty" tf:"kty,omitempty"`
}

type SymmetricJwksKeysObservation struct {
	Alg *string `json:"alg,omitempty" tf:"alg,omitempty"`

	Kid *string `json:"kid,omitempty" tf:"kid,omitempty"`

	Kty *string `json:"kty,omitempty" tf:"kty,omitempty"`
}

type SymmetricJwksKeysParameters struct {

	// +kubebuilder:validation:Optional
	Alg *string `json:"alg,omitempty" tf:"alg,omitempty"`

	// +kubebuilder:validation:Required
	KeySecretRef v1.SecretKeySelector `json:"keySecretRef" tf:"-"`

	// +kubebuilder:validation:Optional
	Kid *string `json:"kid" tf:"kid,omitempty"`

	// +kubebuilder:validation:Optional
	Kty *string `json:"kty,omitempty" tf:"kty,omitempty"`
}

// JWTServerProfileSpec defines the desired state of JWTServerProfile
type JWTServerProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     JWTServerProfileParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider JWTServerProfileInitParameters `json:"initProvider,omitempty"`
}

// JWTServerProfileStatus defines the observed state of JWTServerProfile.
type JWTServerProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        JWTServerProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// JWTServerProfile is the Schema for the JWTServerProfiles API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,avi}
type JWTServerProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="name is a required parameter"
	Spec   JWTServerProfileSpec   `json:"spec"`
	Status JWTServerProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// JWTServerProfileList contains a list of JWTServerProfiles
type JWTServerProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []JWTServerProfile `json:"items"`
}

// Repository type metadata.
var (
	JWTServerProfile_Kind             = "JWTServerProfile"
	JWTServerProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: JWTServerProfile_Kind}.String()
	JWTServerProfile_KindAPIVersion   = JWTServerProfile_Kind + "." + CRDGroupVersion.String()
	JWTServerProfile_GroupVersionKind = CRDGroupVersion.WithKind(JWTServerProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&JWTServerProfile{}, &JWTServerProfileList{})
}
