/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MandatoryMessageInitParameters struct {
	MandatoryMessage []MandatoryMessageMandatoryMessageInitParameters `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryMessagesInitParameters `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryMessageMandatoryMessageInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessageMandatoryMessageObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessageMandatoryMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessageMandatoryMessagesInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessageMandatoryMessagesObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessageMandatoryMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessageObservation struct {
	MandatoryMessage []MandatoryMessageMandatoryMessageObservation `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryMessagesObservation `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryMessageParameters struct {

	// +kubebuilder:validation:Optional
	MandatoryMessage []MandatoryMessageMandatoryMessageParameters `json:"mandatoryMessage" tf:"mandatory_message,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryMessages []MandatoryMessagesParameters `json:"mandatoryMessages" tf:"mandatory_messages,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryString *string `json:"mandatoryString" tf:"mandatory_string,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryStrings []*string `json:"mandatoryStrings" tf:"mandatory_strings,omitempty"`
}

type MandatoryMessagesInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesMandatoryMessageInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesMandatoryMessageObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesMandatoryMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesMandatoryMessagesInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesMandatoryMessagesObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesMandatoryMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestInitParameters struct {
	MandatoryMessage []MandatoryMessageInitParameters `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryTestMandatoryMessagesInitParameters `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestMandatoryMessagesInitParameters struct {
	MandatoryMessage []MandatoryMessagesMandatoryMessageInitParameters `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryMessagesMandatoryMessagesInitParameters `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestMandatoryMessagesObservation struct {
	MandatoryMessage []MandatoryMessagesMandatoryMessageObservation `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryMessagesMandatoryMessagesObservation `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestMandatoryMessagesParameters struct {

	// +kubebuilder:validation:Optional
	MandatoryMessage []MandatoryMessagesMandatoryMessageParameters `json:"mandatoryMessage" tf:"mandatory_message,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryMessages []MandatoryMessagesMandatoryMessagesParameters `json:"mandatoryMessages" tf:"mandatory_messages,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryString *string `json:"mandatoryString" tf:"mandatory_string,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryStrings []*string `json:"mandatoryStrings" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestObservation struct {
	MandatoryMessage []MandatoryMessageObservation `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryTestMandatoryMessagesObservation `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestParameters struct {

	// +kubebuilder:validation:Optional
	MandatoryMessage []MandatoryMessageParameters `json:"mandatoryMessage" tf:"mandatory_message,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryMessages []MandatoryTestMandatoryMessagesParameters `json:"mandatoryMessages" tf:"mandatory_messages,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryString *string `json:"mandatoryString" tf:"mandatory_string,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryStrings []*string `json:"mandatoryStrings" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsInitParameters struct {
	MandatoryMessage []MandatoryTestsMandatoryMessageInitParameters `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryTestsMandatoryMessagesInitParameters `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsMandatoryMessageInitParameters struct {
	MandatoryMessage []MandatoryTestsMandatoryMessageMandatoryMessageInitParameters `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryMessageMandatoryMessagesInitParameters `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsMandatoryMessageMandatoryMessageInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessageMandatoryMessageObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessageMandatoryMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessageObservation struct {
	MandatoryMessage []MandatoryTestsMandatoryMessageMandatoryMessageObservation `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryMessageMandatoryMessagesObservation `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsMandatoryMessageParameters struct {

	// +kubebuilder:validation:Optional
	MandatoryMessage []MandatoryTestsMandatoryMessageMandatoryMessageParameters `json:"mandatoryMessage" tf:"mandatory_message,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryMessages []MandatoryMessageMandatoryMessagesParameters `json:"mandatoryMessages" tf:"mandatory_messages,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryString *string `json:"mandatoryString" tf:"mandatory_string,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryStrings []*string `json:"mandatoryStrings" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsMandatoryMessagesInitParameters struct {
	MandatoryMessage []MandatoryTestsMandatoryMessagesMandatoryMessageInitParameters `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryTestsMandatoryMessagesMandatoryMessagesInitParameters `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsMandatoryMessagesMandatoryMessageInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessagesMandatoryMessageObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessagesMandatoryMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessagesMandatoryMessagesInitParameters struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessagesMandatoryMessagesObservation struct {
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessagesMandatoryMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalString *string `json:"optionalString,omitempty" tf:"optional_string,omitempty"`
}

type MandatoryTestsMandatoryMessagesObservation struct {
	MandatoryMessage []MandatoryTestsMandatoryMessagesMandatoryMessageObservation `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryTestsMandatoryMessagesMandatoryMessagesObservation `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsMandatoryMessagesParameters struct {

	// +kubebuilder:validation:Optional
	MandatoryMessage []MandatoryTestsMandatoryMessagesMandatoryMessageParameters `json:"mandatoryMessage" tf:"mandatory_message,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryMessages []MandatoryTestsMandatoryMessagesMandatoryMessagesParameters `json:"mandatoryMessages" tf:"mandatory_messages,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryString *string `json:"mandatoryString" tf:"mandatory_string,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryStrings []*string `json:"mandatoryStrings" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsObservation struct {
	MandatoryMessage []MandatoryTestsMandatoryMessageObservation `json:"mandatoryMessage,omitempty" tf:"mandatory_message,omitempty"`

	MandatoryMessages []MandatoryTestsMandatoryMessagesObservation `json:"mandatoryMessages,omitempty" tf:"mandatory_messages,omitempty"`

	MandatoryString *string `json:"mandatoryString,omitempty" tf:"mandatory_string,omitempty"`

	MandatoryStrings []*string `json:"mandatoryStrings,omitempty" tf:"mandatory_strings,omitempty"`
}

type MandatoryTestsParameters struct {

	// +kubebuilder:validation:Optional
	MandatoryMessage []MandatoryTestsMandatoryMessageParameters `json:"mandatoryMessage" tf:"mandatory_message,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryMessages []MandatoryTestsMandatoryMessagesParameters `json:"mandatoryMessages" tf:"mandatory_messages,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryString *string `json:"mandatoryString" tf:"mandatory_string,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryStrings []*string `json:"mandatoryStrings" tf:"mandatory_strings,omitempty"`
}

type SensitiveMessageInitParameters struct {
	SensitiveMessage []SensitiveMessageSensitiveMessageInitParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveMessagesInitParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveMessageObservation struct {
	SensitiveMessage []SensitiveMessageSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveMessageParameters struct {

	// +kubebuilder:validation:Optional
	SensitiveMessage []SensitiveMessageSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveMessages []SensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveStringSecretRef *v1.SecretKeySelector `json:"sensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveMessageSensitiveMessageInitParameters struct {
}

type SensitiveMessageSensitiveMessageObservation struct {
}

type SensitiveMessageSensitiveMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveMessageSensitiveMessagesInitParameters struct {
}

type SensitiveMessageSensitiveMessagesObservation struct {
}

type SensitiveMessageSensitiveMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveMessagesInitParameters struct {
}

type SensitiveMessagesObservation struct {
}

type SensitiveMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveMessagesSensitiveMessageInitParameters struct {
}

type SensitiveMessagesSensitiveMessageObservation struct {
}

type SensitiveMessagesSensitiveMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveMessagesSensitiveMessagesInitParameters struct {
}

type SensitiveMessagesSensitiveMessagesObservation struct {
}

type SensitiveMessagesSensitiveMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestInitParameters struct {
	SensitiveMessage []SensitiveMessageInitParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveTestSensitiveMessagesInitParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestObservation struct {
	SensitiveMessage []SensitiveMessageObservation `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveTestSensitiveMessagesObservation `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestParameters struct {

	// +kubebuilder:validation:Optional
	SensitiveMessage []SensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveMessages []SensitiveTestSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveStringSecretRef *v1.SecretKeySelector `json:"sensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestSensitiveMessagesInitParameters struct {
	SensitiveMessage []SensitiveMessagesSensitiveMessageInitParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveMessagesSensitiveMessagesInitParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestSensitiveMessagesObservation struct {
	SensitiveMessage []SensitiveMessagesSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveMessagesSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestSensitiveMessagesParameters struct {

	// +kubebuilder:validation:Optional
	SensitiveMessage []SensitiveMessagesSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveMessages []SensitiveMessagesSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveStringSecretRef *v1.SecretKeySelector `json:"sensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestsInitParameters struct {
	SensitiveMessage []SensitiveTestsSensitiveMessageInitParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveTestsSensitiveMessagesInitParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestsObservation struct {
	SensitiveMessage []SensitiveTestsSensitiveMessageObservation `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveTestsSensitiveMessagesObservation `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestsParameters struct {

	// +kubebuilder:validation:Optional
	SensitiveMessage []SensitiveTestsSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveMessages []SensitiveTestsSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveStringSecretRef *v1.SecretKeySelector `json:"sensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestsSensitiveMessageInitParameters struct {
	SensitiveMessage []SensitiveTestsSensitiveMessageSensitiveMessageInitParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveMessageSensitiveMessagesInitParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestsSensitiveMessageObservation struct {
	SensitiveMessage []SensitiveTestsSensitiveMessageSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveMessageSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestsSensitiveMessageParameters struct {

	// +kubebuilder:validation:Optional
	SensitiveMessage []SensitiveTestsSensitiveMessageSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveMessages []SensitiveMessageSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveStringSecretRef *v1.SecretKeySelector `json:"sensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestsSensitiveMessageSensitiveMessageInitParameters struct {
}

type SensitiveTestsSensitiveMessageSensitiveMessageObservation struct {
}

type SensitiveTestsSensitiveMessageSensitiveMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestsSensitiveMessagesInitParameters struct {
	SensitiveMessage []SensitiveTestsSensitiveMessagesSensitiveMessageInitParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveTestsSensitiveMessagesSensitiveMessagesInitParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestsSensitiveMessagesObservation struct {
	SensitiveMessage []SensitiveTestsSensitiveMessagesSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	SensitiveMessages []SensitiveTestsSensitiveMessagesSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`
}

type SensitiveTestsSensitiveMessagesParameters struct {

	// +kubebuilder:validation:Optional
	SensitiveMessage []SensitiveTestsSensitiveMessagesSensitiveMessageParameters `json:"sensitiveMessage,omitempty" tf:"sensitive_message,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveMessages []SensitiveTestsSensitiveMessagesSensitiveMessagesParameters `json:"sensitiveMessages,omitempty" tf:"sensitive_messages,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveStringSecretRef *v1.SecretKeySelector `json:"sensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestsSensitiveMessagesSensitiveMessageInitParameters struct {
}

type SensitiveTestsSensitiveMessagesSensitiveMessageObservation struct {
}

type SensitiveTestsSensitiveMessagesSensitiveMessageParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type SensitiveTestsSensitiveMessagesSensitiveMessagesInitParameters struct {
}

type SensitiveTestsSensitiveMessagesSensitiveMessagesObservation struct {
}

type SensitiveTestsSensitiveMessagesSensitiveMessagesParameters struct {

	// +kubebuilder:validation:Optional
	OptionalSensitiveStringSecretRef *v1.SecretKeySelector `json:"optionalSensitiveStringSecretRef,omitempty" tf:"-"`
}

type StringLengthMessageInitParameters struct {
	StringLengthMessage []StringLengthMessageStringLengthMessageInitParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthMessagesInitParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthMessageObservation struct {
	StringLengthMessage []StringLengthMessageStringLengthMessageObservation `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthMessagesObservation `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthMessageParameters struct {

	// +kubebuilder:validation:Optional
	StringLengthMessage []StringLengthMessageStringLengthMessageParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthMessages []StringLengthMessagesParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	// +kubebuilder:validation:Optional
	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthMessageStringLengthMessageInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessageStringLengthMessageObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessageStringLengthMessageParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessageStringLengthMessagesInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessageStringLengthMessagesObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessageStringLengthMessagesParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesStringLengthMessageInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesStringLengthMessageObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesStringLengthMessageParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesStringLengthMessagesInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesStringLengthMessagesObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthMessagesStringLengthMessagesParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestInitParameters struct {
	StringLengthMessage []StringLengthMessageInitParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthTestStringLengthMessagesInitParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestObservation struct {
	StringLengthMessage []StringLengthMessageObservation `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthTestStringLengthMessagesObservation `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestParameters struct {

	// +kubebuilder:validation:Optional
	StringLengthMessage []StringLengthMessageParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthMessages []StringLengthTestStringLengthMessagesParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	// +kubebuilder:validation:Optional
	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestStringLengthMessagesInitParameters struct {
	StringLengthMessage []StringLengthMessagesStringLengthMessageInitParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthMessagesStringLengthMessagesInitParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestStringLengthMessagesObservation struct {
	StringLengthMessage []StringLengthMessagesStringLengthMessageObservation `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthMessagesStringLengthMessagesObservation `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestStringLengthMessagesParameters struct {

	// +kubebuilder:validation:Optional
	StringLengthMessage []StringLengthMessagesStringLengthMessageParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthMessages []StringLengthMessagesStringLengthMessagesParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	// +kubebuilder:validation:Optional
	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsInitParameters struct {
	StringLengthMessage []StringLengthTestsStringLengthMessageInitParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthTestsStringLengthMessagesInitParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsObservation struct {
	StringLengthMessage []StringLengthTestsStringLengthMessageObservation `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthTestsStringLengthMessagesObservation `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsParameters struct {

	// +kubebuilder:validation:Optional
	StringLengthMessage []StringLengthTestsStringLengthMessageParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthMessages []StringLengthTestsStringLengthMessagesParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	// +kubebuilder:validation:Optional
	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsStringLengthMessageInitParameters struct {
	StringLengthMessage []StringLengthTestsStringLengthMessageStringLengthMessageInitParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthMessageStringLengthMessagesInitParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsStringLengthMessageObservation struct {
	StringLengthMessage []StringLengthTestsStringLengthMessageStringLengthMessageObservation `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthMessageStringLengthMessagesObservation `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsStringLengthMessageParameters struct {

	// +kubebuilder:validation:Optional
	StringLengthMessage []StringLengthTestsStringLengthMessageStringLengthMessageParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthMessages []StringLengthMessageStringLengthMessagesParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	// +kubebuilder:validation:Optional
	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsStringLengthMessageStringLengthMessageInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessageStringLengthMessageObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessageStringLengthMessageParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessagesInitParameters struct {
	StringLengthMessage []StringLengthTestsStringLengthMessagesStringLengthMessageInitParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthTestsStringLengthMessagesStringLengthMessagesInitParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsStringLengthMessagesObservation struct {
	StringLengthMessage []StringLengthTestsStringLengthMessagesStringLengthMessageObservation `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	StringLengthMessages []StringLengthTestsStringLengthMessagesStringLengthMessagesObservation `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsStringLengthMessagesParameters struct {

	// +kubebuilder:validation:Optional
	StringLengthMessage []StringLengthTestsStringLengthMessagesStringLengthMessageParameters `json:"stringLengthMessage,omitempty" tf:"string_length_message,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthMessages []StringLengthTestsStringLengthMessagesStringLengthMessagesParameters `json:"stringLengthMessages,omitempty" tf:"string_length_messages,omitempty"`

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	// +kubebuilder:validation:Optional
	TestStrings []*string `json:"testStrings,omitempty" tf:"test_strings,omitempty"`
}

type StringLengthTestsStringLengthMessagesStringLengthMessageInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessagesStringLengthMessageObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessagesStringLengthMessageParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessagesStringLengthMessagesInitParameters struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessagesStringLengthMessagesObservation struct {
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type StringLengthTestsStringLengthMessagesStringLengthMessagesParameters struct {

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`
}

type WebappUtConfigpbAttributesInitParameters struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type WebappUtConfigpbAttributesObservation struct {
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type WebappUtConfigpbAttributesParameters struct {

	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type WebappUtInitParameters struct {
	ConfigpbAttributes []WebappUtConfigpbAttributesInitParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	MandatoryTest []MandatoryTestInitParameters `json:"mandatoryTest,omitempty" tf:"mandatory_test,omitempty"`

	MandatoryTests []MandatoryTestsInitParameters `json:"mandatoryTests,omitempty" tf:"mandatory_tests,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	SensitiveTest []SensitiveTestInitParameters `json:"sensitiveTest,omitempty" tf:"sensitive_test,omitempty"`

	SensitiveTests []SensitiveTestsInitParameters `json:"sensitiveTests,omitempty" tf:"sensitive_tests,omitempty"`

	StringLengthTest []StringLengthTestInitParameters `json:"stringLengthTest,omitempty" tf:"string_length_test,omitempty"`

	StringLengthTests []StringLengthTestsInitParameters `json:"stringLengthTests,omitempty" tf:"string_length_tests,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type WebappUtObservation struct {
	ConfigpbAttributes []WebappUtConfigpbAttributesObservation `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	MandatoryTest []MandatoryTestObservation `json:"mandatoryTest,omitempty" tf:"mandatory_test,omitempty"`

	MandatoryTests []MandatoryTestsObservation `json:"mandatoryTests,omitempty" tf:"mandatory_tests,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	SensitiveTest []SensitiveTestObservation `json:"sensitiveTest,omitempty" tf:"sensitive_test,omitempty"`

	SensitiveTests []SensitiveTestsObservation `json:"sensitiveTests,omitempty" tf:"sensitive_tests,omitempty"`

	StringLengthTest []StringLengthTestObservation `json:"stringLengthTest,omitempty" tf:"string_length_test,omitempty"`

	StringLengthTests []StringLengthTestsObservation `json:"stringLengthTests,omitempty" tf:"string_length_tests,omitempty"`

	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type WebappUtParameters struct {

	// +kubebuilder:validation:Optional
	ConfigpbAttributes []WebappUtConfigpbAttributesParameters `json:"configpbAttributes,omitempty" tf:"configpb_attributes,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryTest []MandatoryTestParameters `json:"mandatoryTest,omitempty" tf:"mandatory_test,omitempty"`

	// +kubebuilder:validation:Optional
	MandatoryTests []MandatoryTestsParameters `json:"mandatoryTests,omitempty" tf:"mandatory_tests,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveTest []SensitiveTestParameters `json:"sensitiveTest,omitempty" tf:"sensitive_test,omitempty"`

	// +kubebuilder:validation:Optional
	SensitiveTests []SensitiveTestsParameters `json:"sensitiveTests,omitempty" tf:"sensitive_tests,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthTest []StringLengthTestParameters `json:"stringLengthTest,omitempty" tf:"string_length_test,omitempty"`

	// +kubebuilder:validation:Optional
	StringLengthTests []StringLengthTestsParameters `json:"stringLengthTests,omitempty" tf:"string_length_tests,omitempty"`

	// +kubebuilder:validation:Optional
	TenantRef *string `json:"tenantRef,omitempty" tf:"tenant_ref,omitempty"`

	// +kubebuilder:validation:Optional
	TestSensitiveStringSecretRef *v1.SecretKeySelector `json:"testSensitiveStringSecretRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	TestString *string `json:"testString,omitempty" tf:"test_string,omitempty"`

	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

// WebappUtSpec defines the desired state of WebappUt
type WebappUtSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WebappUtParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WebappUtInitParameters `json:"initProvider,omitempty"`
}

// WebappUtStatus defines the observed state of WebappUt.
type WebappUtStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WebappUtObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// WebappUt is the Schema for the WebappUts API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,avi}
type WebappUt struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="name is a required parameter"
	Spec   WebappUtSpec   `json:"spec"`
	Status WebappUtStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebappUtList contains a list of WebappUts
type WebappUtList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WebappUt `json:"items"`
}

// Repository type metadata.
var (
	WebappUt_Kind             = "WebappUt"
	WebappUt_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WebappUt_Kind}.String()
	WebappUt_KindAPIVersion   = WebappUt_Kind + "." + CRDGroupVersion.String()
	WebappUt_GroupVersionKind = CRDGroupVersion.WithKind(WebappUt_Kind)
)

func init() {
	SchemeBuilder.Register(&WebappUt{}, &WebappUtList{})
}
